services:
  backend:
    build:
      context: ./backend
    env_file:
      - path: ./backend/.env
        required: false
    environment:
      ENVIRONMENT: dev
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - ./backend:/app
